language: php
sudo: false

php:
  - 5.6
  - 7.0
#  - 7.1

env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - MAGETESTSTAND_URL=https://github.com/ambimax/MageTestStand.git
    - secure: "phESHYNkuXa1kKff9xCAk1GqvmIvI+SAqM0CVUAa0shHC5TMjDTnuU6Gtr487R1gQqsxCDndXGIrMogNfER/cdv6tl2zLztpyu5z9jclab82pYby1TZQ74pimqQY3ZDPt6loaM4FMRwLH1Z2yD+IvMGaR0WlKabTPGU20cB10pqtE93RMojAf/+INHXlRn7hCwMhyqziXHoQoCv1g+Wx0J9eb3MhOMysXv9jR/QeV1QVrA0Kg3+PEIICgjyr3I2aQDIScWOXHAeV0RZBNmtDviSIR5RiYuJFMON9dx4Z8DVp9UovSoVuJbiTWgkE+GbYd883DwGEccBDH5hpyL6GW71nvUpB1lYo9cEfuakBTOrggOzacHt/QQtw5GZUaYT9q2IdINIPciwfT7bbS+s2Azo7a67V4U1Gh6OhoYi9FRvvpH0D0Y6Gs+WCgBEUUzwDrOM8HjY1WQQ1ySvCVUtQJTkFkOue/jGMRdAm1yoXdFGj+U6292SL9kwFvKNt3GABY6rgCAtnstxi20wv3NkpUe7pvwKJoBtdehEAHyAnL8CeMy0dWgDm3rt5mbISFvHapteHcnLSTF2pZgzKpq2jafFaRSoJEESNfEZq8Zx3wpDVNjiousMY8zJm586zQSbeajU74EHB/ODUbvHiBtOvXgZo1S54yriAHrSpGe1dR14="

  matrix:
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.9.3.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

addons:
  mariadb: '10.1'

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

script:
  - curl --retry 2 --retry-delay 5 -f -sSL https://raw.githubusercontent.com/ambimax/MageTestStand/TravisCI-AL/setup.sh | bash

after_failure:
  - ls -lah /tmp/mageteststand.*/
  - ls -lah /tmp/mageteststand.*/.modman/
  - ls -lah /tmp/mageteststand.*/.modman/magento-module-ambimax-lazycatalogimages/
  - ls -lah /tmp/mageteststand.*/htdocs/
  - ls -lah /tmp/mageteststand.*/vendor/
  - ls -lah /tmp/mageteststand.*/bin/
  - (cd /tmp/mageteststand.*/ && bin/phpunit --version)

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
